---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: nginx-deployment
  namespace: nginx-redhat
labels:
  app: nginx-deployment
spec:
  clusterSelector:
    matchLabels:
      cloud: Amazon
