apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: redhat-nginx-subscription
  namespace: nginx-redhat
  annotations:
    apps.open-cluster-management.io/github-path: sites/staging-edge.devcluster.openshift.com/03_services/nginx
    apps.open-cluster-management.io/github-branch: master
  labels:
    app: nginx-deployment
spec:
  channel: edge-demo/gitops
  placement:
    placementRef:
      name: nginx-deployment
      kind: PlacementRule


