apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: nginx-virtual-host-ingress-redhat
spec:
  rules:
  - host: redhat-mynginx.apps.staging-edge.devcluster.openshift.com
    http:
      paths:
      - backend:
          serviceName: redhat-nginx-service
          servicePort: 8080
